/* Generated by Yosys 0.9+3891 (git sha1 2f64f961, clang 7.0.1-8+deb10u2 -fPIC -Os) */

module adder(i0, i1, ci, s, co);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input ci;
  output co;
  input [7:0] i0;
  input [7:0] i1;
  output [7:0] s;
  full_adder \fa_f:0.fa_i  (
    .ci(ci),
    .co(_08_),
    .i0(i0[0]),
    .i1(i1[0]),
    .s(_00_)
  );
  full_adder \fa_f:1.fa_i  (
    .ci(_08_),
    .co(_10_),
    .i0(i0[1]),
    .i1(i1[1]),
    .s(_09_)
  );
  full_adder \fa_f:2.fa_i  (
    .ci(_10_),
    .co(_12_),
    .i0(i0[2]),
    .i1(i1[2]),
    .s(_11_)
  );
  full_adder \fa_f:3.fa_i  (
    .ci(_12_),
    .co(_14_),
    .i0(i0[3]),
    .i1(i1[3]),
    .s(_13_)
  );
  full_adder \fa_f:4.fa_i  (
    .ci(_14_),
    .co(_01_),
    .i0(i0[4]),
    .i1(i1[4]),
    .s(_15_)
  );
  full_adder \fa_f:5.fa_i  (
    .ci(_01_),
    .co(_03_),
    .i0(i0[5]),
    .i1(i1[5]),
    .s(_02_)
  );
  full_adder \fa_f:6.fa_i  (
    .ci(_03_),
    .co(_05_),
    .i0(i0[6]),
    .i1(i1[6]),
    .s(_04_)
  );
  full_adder \fa_f:7.fa_i  (
    .ci(_05_),
    .co(_07_),
    .i0(i0[7]),
    .i1(i1[7]),
    .s(_06_)
  );
  assign s = { _06_, _04_, _02_, _15_, _13_, _11_, _09_, _00_ };
  assign co = _07_;
endmodule
